name: Terraform CI/CD for dev, stage, and prod

on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'prod'
    paths:
      - 'OpenTerraAS/infra/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./OpenTerraAS/infra

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform Workspace
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform init
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}
      - name: Terraform Validate
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform validate

  lint:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Lint
        run: |
          cd ${{ env.WORKING_DIR }}
          tflint

  deploy:
    if: github.ref_name != 'prod'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform Workspace
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform init
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}
      - name: Terraform Plan and Apply
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
