name: Deploy infrastructure

on:
  workflow_call:
    inputs:
      WORKSPACE:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: Production
    
    name: 'deploy infrastructure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./OpenTerraAS/infra/
      WORKSPACE: ${{ inputs.WORKSPACE }}
      
    steps:
      - uses: actions/checkout@v4

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      # Set Terraform workspace
      - name: Set Terraform workspace
        run: |
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
        working-directory: ${{ env.WORKING_DIR }}

      # Generate a plan for Terraform changes
      - name: Terraform plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}
      
      # Apply Terraform changes
      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
