# This is a basic workflow to help validate your Terraform configuration

name: Destroy infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'main'
      - 'stage'
      - 'prod'
      - 'dev'
    paths:
      - 'OpenTerraAS/infra/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Destroy"
  terraform:
    name: 'Destroy'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./OpenTerraAS/infra
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      
    # Destroys the infrastructure if the commit message has the word destroy in it
      - name: 'Check last commit message'
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1)"
      - name: 'Conditionally run Terraform action'
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            terraform destroy -auto-approve
          fi
        working-directory: ${{ env.WORKING_DIR }} 
