# The following workflow will just validate and deploy the deveolopment infrastructure
name: Development

on:
  push:
    branches:
      - 'dev'

jobs:
  terraform-validate:
      name: Validate terraform code in dev
      uses: ./.github/workflows/validate_infra.yml
      with:
        WORKSPACE: dev
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
  terraform-deploy:
    needs: terraform-validate
    name: Deploy development infrastructure
    uses: ./.github/workflows/deploy_infra.yml
    with:
      WORKSPACE: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
