name: Production

on:
  push:
    branches:
      - 'main'

jobs:
  terraform-deploy:
    uses: ./.github/workflows/deploy_infra.yml
    with:
      WORKSPACE: prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
