name: Staging

on:
  push:
    branches:
      - 'stage'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Validate
        uses: ./.github/workflows/validate_infra.yml
        with:
          WORKSPACE: stage
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  terraform-lint:
    needs: terraform-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Lint
        uses: ./.github/workflows/tflint.yml

  terraform-deploy:
    needs: terraform-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Deploy
        uses: ./.github/workflows/deploy_infra.yml
        with:
          WORKSPACE: stage
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
