# This is a basic workflow to help validate your Terraform configuration

name: Terraform Linter

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Terraform Validate"]
    types:
      - completed
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Security Check"
  terraform:
    name: 'tflint'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./course materials/module07/demo-infra
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup TFLint
      # You may pin to the exact commit or the version.
      # uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          # TFLint version to install
          tflint_version: default # optional, default is latest
          # GitHub token - used when getting the latest version of tflint
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Installs a wrapper script to wrap subsequent calls to `tflint` and expose `stdout`, `stderr`, and `exitcode` outputs
          tflint_wrapper: false # optional, default is false
