name: Validate Infrastructure

on:
  workflow_call:
    inputs:
      WORKSPACE:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  terraform-validate:
    name: 'Validate'
    runs-on: ubuntu-latest
  
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./OpenTerraAS/infra/
      WORKSPACE: ${{ inputs.WORKSPACE }}
        
    steps:
      - uses: actions/checkout@v4

      # Runs terraform format to check if it is nicely formatted code
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}

      # Runs a single command using the runners shell
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}          

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
